// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXr04xfbgsh-MpQ8wE_gh9EBsubzD-IA',
    appId: '1:274595530214:web:4d86d48959f2030974c227',
    messagingSenderId: '274595530214',
    projectId: 'termproject-27627',
    authDomain: 'termproject-27627.firebaseapp.com',
    storageBucket: 'termproject-27627.appspot.com',
    measurementId: 'G-D0W99FFRTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm45cSdotuZKKpYq0W_3JJWEjt_3ELd34',
    appId: '1:274595530214:android:8e9daeb35ababd2074c227',
    messagingSenderId: '274595530214',
    projectId: 'termproject-27627',
    storageBucket: 'termproject-27627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFWjX_Ap9Vp3HGCqye2nj-QDuvou17L4',
    appId: '1:274595530214:ios:2f5de6abd74cfd5574c227',
    messagingSenderId: '274595530214',
    projectId: 'termproject-27627',
    storageBucket: 'termproject-27627.appspot.com',
    iosClientId: '274595530214-ki13gho89r5fpl5j9gfc1qn12mfkoff0.apps.googleusercontent.com',
    iosBundleId: 'com.example.calender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARFWjX_Ap9Vp3HGCqye2nj-QDuvou17L4',
    appId: '1:274595530214:ios:2f5de6abd74cfd5574c227',
    messagingSenderId: '274595530214',
    projectId: 'termproject-27627',
    storageBucket: 'termproject-27627.appspot.com',
    iosClientId: '274595530214-ki13gho89r5fpl5j9gfc1qn12mfkoff0.apps.googleusercontent.com',
    iosBundleId: 'com.example.calender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXr04xfbgsh-MpQ8wE_gh9EBsubzD-IA',
    appId: '1:274595530214:web:8fc245a76bc32add74c227',
    messagingSenderId: '274595530214',
    projectId: 'termproject-27627',
    authDomain: 'termproject-27627.firebaseapp.com',
    storageBucket: 'termproject-27627.appspot.com',
    measurementId: 'G-1XDQ82218F',
  );
}
